/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:9e1154be-2a88-4dc6-93dc-d522879e61a4",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_XJYKRbzg0",
    "aws_user_pools_web_client_id": "3inab6ifasi0o5mdb35brio2p5",
    "oauth": {},
    "aws_user_files_s3_bucket": "mybookstored067a373a70a4e83a8a87ce1c5f392f1114451-prod",
    "aws_user_files_s3_bucket_region": "ap-northeast-1",
    "aws_appsync_graphqlEndpoint": "https://mzvkxymvwjgszbxzslk2mpukma.appsync-api.ap-northeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-northeast-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-5ym35bw7d5aefecysdtc53m3oe"
};


export default awsmobile;
